### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by mkasprz** [david-mart/vscode-swap-word#3]
Hi,

I'd like to use this extension, but there is no license provided I believe, so I don't even know if I can "officially" compile it and use for commercial use.
Could it be [MIT](https://mit-license.org/) for example? Could You include it?

And thank You for this extension by the way!

**Comment by david-mart** [comment]
Added the license. Please feel free to use this codebase as needed. Sorry for the very late reply.

**Comment by mkasprz** [comment]
Thank You very much! It's ok, forgiven. ;) I appreciate it though! Bless!
